### ISSUE TITLE
Bug #1

### ISSUE THREAD

**Issue by Dermotron** [MScientistCM/March2019ToV6Conversion#10]
there appears to be a phantom cup replacing the League Cup

https://i.postimg.cc/br52bzsZ/phantom-cup.jpg

A decider I am guessing is MLS or Japan related

**Comment by MScientistCM** [comment]
I think this bug was already present in v6 last year, i remember some people complaining the competition got stuck after the semi final, not sure if its the same thing though.

**Comment by MScientistCM** [comment]
I suspect this bug was introduced by this change from v6's changelist:

*EFL Cup matches now go straight to penalties if scores are level after 90 minutes (except for the Final, where extra-time is still played).

That could then be easilly fixed by applying the reversal patch of 'EFL cup tiebreaks.patch' from saturn into an existing v6 .exe.

**Comment by MScientistCM** [comment]
fixed with reversal patch
